### PR TITLE
[Bugfix] No compatible versions available (jq )

### PR DESCRIPTION
**Pull request by zteeed**
```bash
curl https://api.github.com/repos/stedolan/jq/releases -v
...
< location: https://api.github.com/repositories/5101141/releases
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/5101141/releases",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

We need to follow 301 redirection to list available releases and download release (when install)

### CODE REVIEW

**Comment by MPV** [comment]
@AZMCode Could you please take a look at this one?

Installing asdf via this plugin currently fails with:
```shell
$ asdf install jq 1.6
Given version '1.6' did not match any releases. Try list-all to see available options
No URL found for release 1.6
Malformed URL
```
...and:
```shell
$ asdf list-all jq
No compatible versions available (jq )
```

**Comment by MPV** [comment]
> @AZMCode Could you please take a look at this one?
> 
> Installing asdf via this plugin currently fails with:
> 
> ```shell
> $ asdf install jq 1.6
> Given version '1.6' did not match any releases. Try list-all to see available options
> No URL found for release 1.6
> Malformed URL
> ```
> 
> ...and:
> 
> ```shell
> $ asdf list-all jq
> No compatible versions available (jq )
> ```

Never mind — I just got it to work using `asdf plugin update jq`. ✅

**Comment by AZMCode** [comment]
Will take a look at it anyways this evening. I haven't checked PRs in a while

**Comment by zteeed** [comment]
RELEASE_URL has changed since this issue was created, this explain why it works now

```
readonly RELEASES_URL="https://api.github.com/repos/jqlang/jq/releases"
```

**Pull request merged**
